name: "TCP Server Logger"
version: "2.0.1"
slug: "tcp_server_logger"
description: "Jednoduch√Ω TCP server na portu 2000"
arch:
  - amd64
  - armv7
  - aarch64

startup: application
boot: auto

ports:
  2000/tcp: 2000

options: {}
schema: {}

